name: Code Style

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install tools
        run: pip install black isort
      - name: Run Black check
        run: black --check .
      - name: Run isort check
        run: isort --check-only .
